PROGC   START   0
        EXTDEF  LISTC,ENDC
		EXTREF  LISTA,ENDA,LISTB,ENDB
REF1   +LDA     LISTA
REF2   +LDT     LISTB+4
REF3   +LDX    #ENDA-LISTA
LISTC   EQU     *
ENDC    EQU     *
REF4    WORD    ENDA-LISTA+LISTC
REF5    WORD    ENDC-LISTC-10
REF6    WORD    ENDC-LISTC+LISTA-1
REF7    WORD    ENDA-LISTA-(ENDB-LISTB)
REF8    WORD    LISTB-LISTA
        END